#!/bin/bash
#
# 4G only (mitigate downgrade attacks used by IMSI catchers)
#
# righttoprivacy[at]tutanota.com
# Blog / Public Tutorials: https://buymeacoffee.com/politictech/posts
#

modemNum=$(mmcli -L | cut -d "/" -f6 | cut -c 1-3)	# grab current modem number

cat << "EOF"
 _   ___  _______         _______  __    _  ___      __   __ 
| | |   ||       |       |       ||  |  | ||   |    |  | |  |
| |_|   ||    ___| ____  |   _   ||   |_| ||   |    |  |_|  |
|       ||   | __ |____| |  | |  ||       ||   |    |       |
|___    ||   ||  |       |  |_|  ||  _    ||   |___ |_     _|
    |   ||   |_| |       |       || | |   ||       |  |   |  
    |___||_______|       |_______||_|  |__||_______|  |___|  
EOF

sleep .5

echo -e "\n"

echo -e "Modem Number Now: $modemNum\n"
sleep .5
echo -e "Setting 4G Only To Mitigate IMSI Catcher Downgrade Attacks"

mmcli -m $modemNum --set-allowed-modes=4g
sleep .5
echo -e "Printing Current Modem Settings...\n" && sleep 1

mmcli -m $modemNum

if [ "$1" = 'reset' ]; then
	echo -e "Replacing 4G Only With 4G Preferred\n"
	mmcli -m $modemNum --set-allowed-modes='3g|4g' --set-preferred-mode='4g'
	echo -e "Now Printing New Output...\n"
	mmcli -m $modemNum
	exit 1
fi
